# fly.toml app configuration file generated for telegram-monitor-curious-harborwave-5208 on 2026-07-13T05:56:04+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'telegram-monitor-curious-harborwave-5208'
primary_region = 'sin'

[build]

[processes]
  app = "python3 monitor.py"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

